@startuml CareCommunicationHeaderHeader

hide empty members


class "MedComCareCommunicationMessageHeader" as messageHeader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as organization
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCoreEncounter" as encounter
class "Organization" as recipientOrganization
class "PractitionerRole" as recipientRole
class "Practitioner" as author

messageHeader -- communication

messageHeader -- organization : "sender"
messageHeader -- organization : "receiver"
messageHeader --"*" organization : "carbon-copy"

communication -- patient : "subject"
communication -- encounter
communication --"0..1" recipientOrganization : "sender"
communication --"0..1" recipientRole : "sender"
communication --"*" recipientOrganization : "recipient"
communication --"*" recipientRole : "recipient"
communication --"1...*" author : "author"

patient - encounter
@enduml