@startuml CareCommunicationMessageHeader

hide empty members

class "MedComCareCommunicationMessageHeader" as messageheader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as messagingOrganization 
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCoreEncounter" as encounter
class "Organization" as recipientOrganization <<MedComMessagingOrganization>>
class "PractitionerRole" as recipientRole
class "Practitioner" as author


messageheader -- messagingOrganization : "sender"
messageheader -- messagingOrganization : "reciever"
messageheader -- communication : "focus"
communication -- encounter : "encounter"
communication -- patient : "subject"
communication -- recipientOrganization : "sender"
communication -- recipientRole : "sender"
communication -- recipientOrganization : "recipient"
communication -- recipientRole : "recipient"
communication -- author : "payload author"

encounter -patient :"subject"
@enduml