@startuml CareCommunication

hide empty members

class "MedComCareCommunicationMessage" as message <<MedComMessagingMessage>>
class "MedComcfa96109-49f3-4d78-a6b7-2c218b34d70a" as messageHeader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as organization
class "MedComCareCommunication" as communication
class "MedComCorePatient" as patient
class "MedComCoreEncounter" as encounter
class "MedComMessagingProvenance" as provenance
class "Organization" as recipientOrganization
class "PractitionerRole" as recipientRole
class "Practitioner" as author

message -- messageHeader
messageHeader -- communication
message -- provenance

messageHeader -- organization : "sender"
messageHeader -- organization : "receiver"
messageHeader --"*" organization : "carbon-copy"

communication -- patient
communication -- encounter
communication --"0..1" recipientOrganization : "sender"
communication --"0..1" recipientRole : "sender"
communication --"*" recipientOrganization : "recipient"
communication --"*" recipientRole : "recipient"
communication --"1...*" author : "author"

patient - encounter
@enduml