@startuml HospitalNotificationMessageHeader

hide empty members


class "MedComHospitalNotificationMessageHeader" as messageHeader <<MedComMessagingMessageHeader>>
class "MedComMessagingOrganization" as organization
class "MedComCorePatient" as patient
class "MedComHospitalNotificationEncounter" as encounter <<MedComCoreEncounter>>
class "MedComCoreOrganization" as serviceProvider


messageHeader -- encounter
encounter -- patient : "subject"
encounter -- serviceProvider : "service provider"


messageHeader -- organization : "sender"
messageHeader -- organization : "receiver"

@enduml
