@startuml HospitalNotificationEncounter

hide empty members

class "MedComHospitalNotificationEncounter" as encounter <<MedComCoreEncounter>>
class "MedComCorePatient" as patient
class "MedComCoreOrganization" as serviceProvider

encounter -- patient : "subject"
encounter -- serviceProvider : "service provider"



@enduml
